### ISSUE TITLE
IllegalStateException: Could not write to text file: D:\projects\IDEasy\workspaces\main\.idea\.name

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#1385]
```
java.lang.IllegalStateException: Could not write to text file: D:\projects\IDEasy\workspaces\main\.idea\.name
        at com.devonfw.tools.ide.merge.TextMerger.merge(TextMerger.java:52)
        at com.devonfw.tools.ide.merge.DirectoryMerger.merge(DirectoryMerger.java:64)
        at com.devonfw.tools.ide.merge.DirectoryMerger.merge(DirectoryMerger.java:68)
        at com.devonfw.tools.ide.merge.DirectoryMerger.merge(DirectoryMerger.java:68)
        at com.devonfw.tools.ide.tool.ide.IdeToolCommandlet.configureWorkspace(IdeToolCommandlet.java:235)
        at com.devonfw.tools.ide.tool.ide.IdeToolCommandlet.run(IdeToolCommandlet.java:200)
        at com.devonfw.tools.ide.context.AbstractIdeContext.applyAndRun(AbstractIdeContext.java:897)
        at com.devonfw.tools.ide.context.AbstractIdeContext.run(AbstractIdeContext.java:847)
        at com.devonfw.tools.ide.cli.Ideasy.runOrThrow(Ideasy.java:92)
        at com.devonfw.tools.ide.cli.Ideasy.run(Ideasy.java:52)
        at com.devonfw.tools.ide.cli.Ideasy.main(Ideasy.java:28)
        at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: java.nio.file.NoSuchFileException: D:\projects\IDEasy\workspaces\main\.idea\.name
        at java.base@21.0.2/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:234)
        at java.base@21.0.2/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:482)
        at java.base@21.0.2/java.nio.file.Files.newOutputStream(Files.java:227)
        at java.base@21.0.2/java.nio.file.Files.write(Files.java:3492)
        at com.devonfw.tools.ide.merge.TextMerger.merge(TextMerger.java:50)
        ... 11 more
```

TextMerger does not create parent directory.

**Comment by hohwille** [comment]
Wrong github project/repository.
If this still happens it needs to be created as new issue here:
https://github.com/devonfw/IDEasy/issues/new
