### ISSUE TITLE
Build does not work with Java11

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#282]
### Expected behavior

As a developer, I want to build `sonar-devon4j-plugin` with Java11 so that I can use `devon-ide` and the recent defaults and I do not need a Java8 what gets out of free support and requires payment for security fixes.

### Actual behavior

build fails (all Tests fail):
```
java.lang.AssertionError: Semantic was required but it was not possible to create it. Please checks the logs to find out the reason.
	at org.sonar.java.checks.verifier.JavaCheckVerifier.scanFile(JavaCheckVerifier.java:272)
	at org.sonar.java.checks.verifier.JavaCheckVerifier.scanFile(JavaCheckVerifier.java:256)
	at org.sonar.java.checks.verifier.JavaCheckVerifier.scanFile(JavaCheckVerifier.java:222)
	at org.sonar.java.checks.verifier.JavaCheckVerifier.verify(JavaCheckVerifier.java:105)
	at com.devonfw.ide.sonarqube.common.impl.check.thirdparty.DevonArchitecture3rdPartyHibernateCheckTest.testNonDataAccess(DevonArchitecture3rdPartyHibernateCheckTest.java:27)
```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. install and configure Java11 (e.g. use `devon-ide` with default settings)
2. run `mvn clean install` on `sonar-devon4j-plugin`

### Related/Dependent Issues
https://github.com/devonfw/devon4j/issues/16

### Comments/Hints:
We might need an update of our SonarQube dependencies.

### Affected version:
Java11, works fine with Java8

**Comment by hohwille** [comment]
sorry, wrong repository. Just ignore this, please.
