### ISSUE TITLE
Deadlocks in Eclipse 2019-09

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#283]
The Eclipse bugtracker is very messy so I file the issue initially here to collect some more feedback and details. However, bugs in Eclipse are not really a bug of devon-ide. Anyhow, we might want to downgrade (getting other bugs) or at least we want to inform our users and discuss options and impact.
So I experience some kind of deadlock in Eclipse on MacOS. It seems to happen during refactoring or immediately after when opening another type.

**Comment by hohwille** [comment]
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x00007fff4239765d, pid=65805, tid=775
#
# JRE version: OpenJDK Runtime Environment (11.0.4+11) (build 11.0.4+11)
# Java VM: OpenJDK 64-Bit Server VM (11.0.4+11, mixed mode, tiered, compressed oops, g1 gc, bsd-amd64)
# Problematic frame:
# C  [AppKit+0x9965d]  -[NSWindow retain]+0x1f
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /projects/software/default/eclipse/2019-09/Eclipse.app/Contents/MacOS/hs_err_pid65805.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-build/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
/projects/mmm/software/eclipse/eclipse: line 3: 65805 Abort trap: 6           "${ECLIPSE_HOME}/Eclipse.app/Contents/MacOS/eclipse" $@
```

**Comment by hohwille** [comment]
Also interesting that I could not create a threaddump as the process/JVM was so heavily stalled that it could not repsond anymore (I tried many times always with the same result):
```
jstack 65805
65805: Unable to open socket file /var/folders/f2/vwk0pngx4kz2178r27dyx1bm0000gn/T/.java_pid65805: target process 65805 doesn't respond within 10500ms or HotSpot VM not loaded
```

This may indicate that the problem is even in native code such as SWT.

**Comment by hohwille** [comment]
I am facing this error now multiple times a day what is very nasty and makes Eclipse usage a pain.
Any other experience? Maybe this is MacOS specific or I am having very exotic setups?

**Comment by hohwille** [comment]
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/projects/software/default/eclipse/2019-09/Eclipse.app/Contents/Eclipse/configuration/org.eclipse.osgi/55/0/.cp/lib/xstream-1.3.1.jar) to field java.util.Properties.defaults
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "Info view input computer" java.lang.IllegalArgumentException: single (not open) [in NlsArguments [in [Working copy] NlsArguments.java [in net.sf.mmm.nls.argument [in src/main/java [in mmm-nls]]]]] does not exist
	at org.eclipse.jdt.core.dom.CompilationUnitResolver$1Requestor.acceptAST(CompilationUnitResolver.java:820)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:933)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:614)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:832)
	at org.eclipse.jdt.core.dom.ASTParser.createBindings(ASTParser.java:1075)
	at org.eclipse.jdt.internal.ui.infoviews.JavadocView.computeFieldConstantFromTypeAST(JavadocView.java:1376)
	at org.eclipse.jdt.internal.ui.infoviews.JavadocView.computeFieldConstant(JavadocView.java:1327)
	at org.eclipse.jdt.internal.ui.infoviews.JavadocView.getJavadocHtml(JavadocView.java:1083)
	at org.eclipse.jdt.internal.ui.infoviews.JavadocView.computeInput(JavadocView.java:894)
	at org.eclipse.jdt.internal.ui.infoviews.AbstractInfoView$2.run(AbstractInfoView.java:761)
Caused by: Java Model Exception: Java Model Status [single [in NlsArguments [in [Working copy] NlsArguments.java [in net.sf.mmm.nls.argument [in src/main/java [in mmm-nls]]]]] does not exist]
	at org.eclipse.jdt.internal.core.JavaElement.newNotPresentException(JavaElement.java:573)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:614)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:326)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:312)
	at org.eclipse.jdt.internal.core.Member.getNameRange(Member.java:353)
	at org.eclipse.jdt.internal.core.util.DOMFinder.search(DOMFinder.java:81)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver$1Requestor.acceptAST(CompilationUnitResolver.java:818)
	... 9 more
Exception in thread "Info view input computer" java.lang.IllegalArgumentException: c (not open) [in NlsMessageFactory [in [Working copy] NlsMessageFactory.java [in net.sf.mmm.nls [in src/main/java [in mmm-nls]]]]] does not exist
	at org.eclipse.jdt.core.dom.CompilationUnitResolver$1Requestor.acceptAST(CompilationUnitResolver.java:820)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:933)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:614)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:832)
	at org.eclipse.jdt.core.dom.ASTParser.createBindings(ASTParser.java:1075)
	at org.eclipse.jdt.internal.ui.infoviews.JavadocView.computeFieldConstantFromTypeAST(JavadocView.java:1376)
	at org.eclipse.jdt.internal.ui.infoviews.JavadocView.computeFieldConstant(JavadocView.java:1327)
	at org.eclipse.jdt.internal.ui.infoviews.JavadocView.getJavadocHtml(JavadocView.java:1083)
	at org.eclipse.jdt.internal.ui.infoviews.JavadocView.computeInput(JavadocView.java:894)
	at org.eclipse.jdt.internal.ui.infoviews.AbstractInfoView$2.run(AbstractInfoView.java:761)
Caused by: Java Model Exception: Java Model Status [c [in NlsMessageFactory [in [Working copy] NlsMessageFactory.java [in net.sf.mmm.nls [in src/main/java [in mmm-nls]]]]] does not exist]
	at org.eclipse.jdt.internal.core.JavaElement.newNotPresentException(JavaElement.java:573)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:614)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:326)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:312)
	at org.eclipse.jdt.internal.core.Member.getNameRange(Member.java:353)
	at org.eclipse.jdt.internal.core.util.DOMFinder.search(DOMFinder.java:81)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver$1Requestor.acceptAST(CompilationUnitResolver.java:818)
```

**Comment by hohwille** [comment]
Meanwhile some plugin updates seem to have fixed this.
