### ISSUE TITLE
Comments in vscode settings causes error when starting vscode

### ISSUE THREAD

**Issue by JanRaber** [devonfw/ide#586]
### Expected behavior

As a software developer, I want to comment my vscode settings so that I can provide additional information in `settings.json`.
For that purpose vscode has a *JSON with comments (jsonc) mode* [link to documentation](https://code.visualstudio.com/docs/languages/json#_json-with-comments) 

### Actual behavior

When using comments in `settings.json`, it works for vscode but devon-ide-configurator produces an error on the next startup of vscode because comments are not part of the default JSON specification. See log below.

```
$ devon vscode
2021-07-01T11:25:59.808+02:00 [SEVERE ] Configurator failed: Failed to read JSON from C:\<path-to-devon>\workspaces\main\.vscode\.userdata\User\settings.json
java.lang.IllegalStateException: Failed to read JSON from C:\<path-to-devon>\workspaces\main\.vscode\.userdata\User\settings.json
        at com.devonfw.tools.ide.configurator.merge.JsonMerger.load(JsonMerger.java:77)
        at com.devonfw.tools.ide.configurator.merge.JsonMerger.merge(JsonMerger.java:47)
        at com.devonfw.tools.ide.configurator.merge.DirectoryMerger.merge(DirectoryMerger.java:67)
        at com.devonfw.tools.ide.configurator.merge.DirectoryMerger.merge(DirectoryMerger.java:71)
        at com.devonfw.tools.ide.configurator.merge.DirectoryMerger.merge(DirectoryMerger.java:71)
        at com.devonfw.tools.ide.configurator.merge.DirectoryMerger.merge(DirectoryMerger.java:71)
        at com.devonfw.tools.ide.configurator.merge.DirectoryMerger.merge(DirectoryMerger.java:71)
        at com.devonfw.tools.ide.configurator.Configurator.createOrUpdateWorkspace(Configurator.java:86)
        at com.devonfw.tools.ide.configurator.Configurator.run(Configurator.java:210)
        at com.devonfw.tools.ide.configurator.Configurator.main(Configurator.java:250)
Caused by: javax.json.stream.JsonParsingException: Unexpected char 47 at (line no=3, column no=5, offset=7)
        at org.glassfish.json.JsonTokenizer.unexpectedChar(JsonTokenizer.java:601)
        at org.glassfish.json.JsonTokenizer.nextToken(JsonTokenizer.java:418)
        at org.glassfish.json.JsonParserImpl$ObjectContext.getNextEvent(JsonParserImpl.java:466)
        at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:376)
        at org.glassfish.json.JsonParserImpl.getObject(JsonParserImpl.java:335)
        at org.glassfish.json.JsonParserImpl.getObject(JsonParserImpl.java:173)
        at org.glassfish.json.JsonReaderImpl.read(JsonReaderImpl.java:94)
        at com.devonfw.tools.ide.configurator.merge.JsonMerger.load(JsonMerger.java:75)
        ... 9 more
Failed to run command: java -cp '/c/<path-to-devon>/scripts/lib/devonfw-ide-configurator-2021.04.001.jar:/c/<path-to-devon>/scripts/lib/javax.json-1.1.4.jar:/c/<path-to-devon>/scripts/lib/javax.json-api-1.1.4.jar' com.devonfw.tools.ide.configurator.Configurator -t /c/<path-to-devon>/settings/vscode/workspace -w /c/<path-to-devon>/workspaces/main -v /c/<path-to-devon>/settings/vscode/workspace/replacement-patterns.properties -u

******** ATTENTION ********
ERROR: Failed to run command java
We are sorry for the inconvenience. Please check the above errors, resolve them and try again.
Exit code was 127
```

### Steps to reproduce (bug)

1. Add a comment (`//` or `/* */`) in `settings.json` 
2. Restart vscode using devon

### Affected version:

* OS: Windows

**Comment by maybeec** [comment]
Json does not allow comments by language specification.

**Comment by JanRaber** [comment]
Hi @maybeec, thank you for your answer. I'm aware of the json language specification. That's why I mentioned, that VS Code is using it's own json specification for `settings.json`, `launch.json` and `tasks.json`. You can find details in the [VS Code documentation](https://code.visualstudio.com/docs/languages/json#_json-with-comments).

In a regular VS Code installation without using Devon, you are able to comment these files. When using Devon you can still comment these files without breaking VS Code itself, but the next time you start VS Code using `devon vscode` you will get the error message described in this issue. So when migrating from a system installation to Devon you have to remove all comments from your settings, launch and tasks, which means you lose information about why settings are made and what influence they have on VS Code.

**Comment by hohwille** [comment]
Problem is that we are using a JSON parser that does not support such comments.
PRs to change this are welcome.
But please understand that it is low priority for us to replace a standard JSON parser and find an alternative that supports this inofficial extension for the sake of comments.
I clearly see your case, but at the moment we have to live without comments as a simple workaround.
Either blame the makers of JSON, file an issue in JSON-P implementation and ask for support of comments, or create a PR that changes devonfw-ide configurator to use a somewhat different JSON parser supporting comments yourself.

**Comment by hohwille** [comment]
Closing as stale for very long time.
